// Apple JWS verification and the apple-subscription Edge Function, exercised with a throwaway
// certificate chain generated by openssl (synthetic: real Apple certificates cannot sign test data).
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
function loader(stubs={},context={}){const cache=new Map();const load=file=>{file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const m={exports:{}};cache.set(file,m);
 const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
 new Function('require','module','exports',...Object.keys(context),source)(id=>{if(id in stubs)return stubs[id];if(id.startsWith('.')){let p=path.resolve(path.dirname(file),id);if(!/\.tsx?$/.test(p))p+='.ts';return load(p);}return require(id);},m,m.exports,...Object.values(context));return m.exports;};return load;}
let openssl=true;try{execFileSync('openssl',['version'])}catch{openssl=false}
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'apple-jws-'));
const run=(...a)=>execFileSync('openssl',a,{cwd:dir,stdio:'pipe'});
function chain(name,{leafMarker=true,intermediateMarker=true}={}){
 const p=f=>`${name}-${f}`;
 fs.writeFileSync(path.join(dir,p('int.ext')),`basicConstraints=critical,CA:true\n${intermediateMarker?'1.2.840.113635.100.6.2.1=ASN1:NULL\n':''}`);
 fs.writeFileSync(path.join(dir,p('leaf.ext')),`basicConstraints=critical,CA:false\n${leafMarker?'1.2.840.113635.100.6.11.1=ASN1:NULL\n':''}`);
 run('ecparam','-name','secp384r1','-genkey','-noout','-out',p('root.key'));
 run('req','-new','-x509','-key',p('root.key'),'-sha384','-days','3650','-subj','/CN=Test Root','-out',p('root.pem'));
 run('ecparam','-name','secp384r1','-genkey','-noout','-out',p('int.key'));
 run('req','-new','-key',p('int.key'),'-subj','/CN=Test Intermediate','-out',p('int.csr'));
 run('x509','-req','-in',p('int.csr'),'-CA',p('root.pem'),'-CAkey',p('root.key'),'-CAcreateserial','-sha384','-days','3650','-extfile',p('int.ext'),'-out',p('int.pem'));
 run('ecparam','-name','prime256v1','-genkey','-noout','-out',p('leaf.key'));
 run('req','-new','-key',p('leaf.key'),'-subj','/CN=Test Leaf','-out',p('leaf.csr'));
 run('x509','-req','-in',p('leaf.csr'),'-CA',p('int.pem'),'-CAkey',p('int.key'),'-CAcreateserial','-sha384','-days','3650','-extfile',p('leaf.ext'),'-out',p('leaf.pem'));
 const der=f=>new crypto.X509Certificate(fs.readFileSync(path.join(dir,p(f)))).raw;
 const x5c=['leaf.pem','int.pem','root.pem'].map(f=>der(f).toString('base64'));
 return {x5c,key:fs.readFileSync(path.join(dir,p('leaf.key'))),fingerprint:crypto.createHash('sha256').update(der('root.pem')).digest('hex')};
}
const b64u=v=>Buffer.from(typeof v==='string'?v:JSON.stringify(v)).toString('base64url');
const sign=(c,payload,x5c=c.x5c)=>{const h=b64u({alg:'ES256',x5c}),p=b64u(payload);return `${h}.${p}.${crypto.sign('sha256',Buffer.from(`${h}.${p}`),{key:c.key,dsaEncoding:'ieee-p1363'}).toString('base64url')}`;};
const RID='11111111-1111-4111-8111-111111111111';
const tx=(o={})=>({bundleId:'app.myrealtor',productId:'monthly.sub',environment:'Sandbox',type:'Auto-Renewable Subscription',originalTransactionId:'2000000000000001',transactionId:'2000000000000002',expiresDate:Date.now()+30*86400000,signedDate:Date.now(),appAccountToken:RID.toUpperCase(),...o});
const opts={skip:!openssl&&'openssl unavailable'};

test('Apple JWS: only a valid chain pinned to the configured root, with Apple markers and a valid signature, verifies',opts,async()=>{
 const {verifyAppleJws,APPLE_ROOT_CA_G3_SHA256}=loader()(path.join(root,'supabase/functions/apple-subscription/appleJws.ts'));
 assert.equal(APPLE_ROOT_CA_G3_SHA256,'63343abfb89a6a03ebb57e9b3f5fa7be7c4f5c756f3017b3a8c488c3653e9179');
 const c=chain('good'),verify={rootFingerprints:[c.fingerprint]};
 const jws=sign(c,tx());
 assert.equal((await verifyAppleJws(jws,verify)).originalTransactionId,'2000000000000001');
 await assert.rejects(verifyAppleJws(jws),/Untrusted root/,'production pin rejects any non-Apple root');
 const [h,,s]=jws.split('.');await assert.rejects(verifyAppleJws(`${h}.${b64u(tx({expiresDate:Date.now()+9e12}))}.${s}`,verify),/Invalid signature/);
 const other=chain('other');await assert.rejects(verifyAppleJws(sign(c,tx(),[c.x5c[0],other.x5c[1],c.x5c[2]]),verify),/chain/);
 const noLeaf=chain('noleaf',{leafMarker:false});await assert.rejects(verifyAppleJws(sign(noLeaf,tx()),{rootFingerprints:[noLeaf.fingerprint]}),/App Store signing certificate/);
 const noInt=chain('noint',{intermediateMarker:false});await assert.rejects(verifyAppleJws(sign(noInt,tx()),{rootFingerprints:[noInt.fingerprint]}),/intermediate/);
 await assert.rejects(verifyAppleJws('a.b'),/Invalid signed value/);
});

test('transaction and notification snapshots enforce app, product and environment, and report billing state only from Apple',opts,async()=>{
 const core=loader()(path.join(root,'supabase/functions/apple-subscription/core.ts'));
 assert.equal(core.appleConfig(()=>undefined),null,'never invents product IDs');
 assert.equal(core.appleConfig(k=>({APPLE_BUNDLE_ID:'app.myrealtor'})[k]),null);
 const c=chain('snap');const config={...core.appleConfig(k=>({APPLE_BUNDLE_ID:'app.myrealtor',APPLE_SUBSCRIPTION_PRODUCT_IDS:'monthly.sub, annual.sub'})[k]),verify:{rootFingerprints:[c.fingerprint]}};
 const r=await core.transactionSnapshot(sign(c,tx()),config);
 assert.equal(r.appAccountToken,RID);assert.equal(r.snapshot.original_transaction_id,'2000000000000001');assert.equal(r.snapshot.product_id,'monthly.sub');
 for(const [bad,re] of [[{bundleId:'com.other'},/another app/],[{productId:'other'},/Unknown subscription/],[{environment:'Xcode'},/environment/],[{type:'Consumable'},/Not a subscription/]])
  await assert.rejects(core.transactionSnapshot(sign(c,tx(bad)),config),re);
 const note=(type,renewal,t=tx())=>sign(c,{notificationType:type,signedDate:Date.now(),data:{bundleId:'app.myrealtor',signedTransactionInfo:sign(c,t),signedRenewalInfo:renewal?sign(c,{signedDate:Date.now(),...renewal}):undefined}});
 const grace=Date.now()+16*86400000;
 const failed=await core.notificationSnapshot(note('DID_FAIL_TO_RENEW',{autoRenewStatus:1,isInBillingRetryPeriod:true,gracePeriodExpiresDate:grace},tx({expiresDate:Date.now()-1000})),config);
 assert.equal(failed.snapshot.billing_issue,true);assert.equal(Date.parse(failed.snapshot.expires_at),grace,'service continues through Apple grace period');
 const renewed=await core.notificationSnapshot(note('DID_RENEW',{autoRenewStatus:1,isInBillingRetryPeriod:false}),config);assert.equal(renewed.snapshot.billing_issue,false);assert.equal(renewed.snapshot.auto_renew,true);
 const off=await core.notificationSnapshot(note('DID_CHANGE_RENEWAL_STATUS',{autoRenewStatus:0}),config);assert.equal(off.snapshot.auto_renew,false);assert.equal(off.snapshot.billing_issue,null,'no billing claim without Apple saying so');
 assert.equal(await core.notificationSnapshot(sign(c,{notificationType:'TEST',signedDate:Date.now(),data:{bundleId:'app.myrealtor'}}),config),null);
});

test('apple-subscription endpoint: not configured, auth, account binding and notifications',opts,async()=>{
 const c=chain('handler');let handler;const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'service',APPLE_BUNDLE_ID:'app.myrealtor',APPLE_SUBSCRIPTION_PRODUCT_IDS:'monthly.sub'};
 const applied=[];let owner=null;
 const db={auth:{getUser:async jwt=>({data:{user:jwt==='realtor'?{id:'auth-realtor'}:jwt==='anon'?{id:'a',is_anonymous:true}:null},error:null})},
  from:()=>({select:()=>({eq:(_k,v)=>({maybeSingle:async()=>({data:v==='auth-realtor'?{id:RID}:null})})})}),
  rpc:async(name,args)=>{if(name==='apple_apply'){applied.push(args);return {data:{ok:true,active:true},error:null};}if(name==='apple_realtor')return {data:owner,error:null};throw new Error(name);}};
 // Inject the test root by wrapping the verifier the core module imports.
 const jwsModule=loader()(path.join(root,'supabase/functions/apple-subscription/appleJws.ts'));
 const pinned={...jwsModule,verifyAppleJws:(j,o)=>jwsModule.verifyAppleJws(j,{...o,rootFingerprints:[c.fingerprint]})};
 const load=loader({'npm:@supabase/supabase-js@2':{createClient:()=>db},'./appleJws.ts':pinned},{Deno:{env:{get:k=>env[k]},serve:fn=>{handler=fn;}}});
 load(path.join(root,'supabase/functions/apple-subscription/index.ts'));
 const call=(body,jwt)=>handler(new Request('https://edge.example/apple-subscription',{method:'POST',headers:{'content-type':'application/json',...(jwt?{authorization:`Bearer ${jwt}`}:{})},body:JSON.stringify(body)}));
 assert.equal((await call({action:'sync',signedTransactions:[sign(c,tx())]})).status,401);
 assert.equal((await call({action:'sync',signedTransactions:[sign(c,tx())]},'anon')).status,401);
 let r=await (await call({action:'sync',signedTransactions:[sign(c,tx())]},'realtor')).json();assert.equal(r.ok,true);assert.equal(applied.at(-1).p_realtor_id,RID);
 r=await (await call({action:'sync',signedTransactions:[sign(c,tx({appAccountToken:'22222222-2222-4222-8222-222222222222'}))]},'realtor')).json();
 assert.equal(r.ok,false);assert.equal(r.results[0].reason,'other_account','a receipt bought for another account cannot unlock this one');
 assert.equal((await call({signedPayload:'forged.payload.sig'})).status,400);
 const n=sign(c,{notificationType:'EXPIRED',signedDate:Date.now(),data:{bundleId:'app.myrealtor',signedTransactionInfo:sign(c,tx({appAccountToken:undefined}))}});
 assert.equal((await (await call({signedPayload:n})).json()).unmatched,true);
 owner=RID;const count=applied.length;assert.equal((await (await call({signedPayload:n})).json()).ok,true);assert.equal(applied.length,count+1);
 delete env.APPLE_SUBSCRIPTION_PRODUCT_IDS;assert.equal((await call({action:'sync',signedTransactions:['x']},'realtor')).status,503);
});
